  import { Character } from './character';

  export const CHARS: Character[] = [
    { uri: 'monte-velho', images: ['assets/imgs/montevelho.png','assets/imgs/montevelho1.png','assets/imgs/montevelho2.png'], name: 'Monte Velho', title: 'Um clássico alentejano', description: 'Monte Velho é hoje um clássico alentejano e uma fiel tradução do território que lhe dá origem. Ao longo dos anos, tornou-se numa referência maior da região. Produzidos na Herdade do Esporão revelam o caráter típico da região onde nascem: aromas ricos, paladar suave e excelente aptidão gastronómica.' },
    { uri: 'esporao', images: ['assets/imgs/esporao.png','assets/imgs/esporao1.jpg','assets/imgs/esporao2.jpg'], name: 'Esporão', title:'A arte nos vinhos', description: 'Ao longo dos anos, os vinhos Esporão tornaram-se vinhos emblemáticos da região do Alentejo e de Portugal, no país e no estrangeiro. A aliança entre a cultura universal do vinho e as Artes plásticas, representa o caráter único da marca Esporão.' },
    { uri: 'alandra', images: ['assets/imgs/alandra.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Alandra', title: 'Vinho entrada de gama',  description: 'Alandra é considerado um vinho ideal para momentos mais descontraídos. Para acompanhar refeições leves. Vai bem com o prato do dia. Ótimo para beber a copo, ideal para juntar a uma sangria, e perfeito para um piquenique em família ou com um grupo de amigos. ' },
    { uri: 'defesa-do-esporao',images: ['assets/imgs/defesa.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Defesa do Esporão', title:'Contemporâneo', description: 'Com um estilo contemporâneo, perfil elegante e intenso, estes vinhos mostram o carácter de talhões selecionados e bem defindos na Herdade.' },
    { uri: 'torre', images:['assets/imgs/torre.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Torre', title: 'O que de melhor se produz', description: 'Produzido apenas nos anos que a natureza oferece condições excecionais, o Torre exprime o que de melhor produzimos na Herdade do Esporão. 2007 foi apenas a segunda colheita deste vinho de topo do Esporão, produzido a partir de vinhas com uma média de 20 anos. ' },
    { uri: 'assobio', images:['assets/imgs/assobio.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Assobio', title:'Um tinto vibrante', description: 'Produzido com as castas Touriga Nacional, Tinta roriz e Touriga Franca, colhidas na Quinta dos Murças, o Assobio é um vinho que expressa o aroma vibrante das castas mais tradicionais do Douro e o seu potencial para vinhos equilibrados e de grande aptidão gastronómica. Cerca de 20% do primeiro lote estagia em barricas novas e usadas de carvalho francês e americano durante doze meses. O vinho da colheita 2011 foi reconhecido como best buy pela revista internacional Wine Enthusiast com 94 pontos.' },
    { uri: 'magistra', images:['assets/imgs/magistra.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Magistra', title: 'Aguardente de qualidade superior',  description: 'Esta aguardente nasce e cresce na região da Lourinhã. É portanto uma DOC Lourinhã, a primeira região demarcada de aguardentes em Portugal e uma das três únicas do mundo, a par com as francesas Cognac e Armagnac. Aguardente produzida com uma graduação média de 70 graus sendo imediatamente colocada em barricas novas de Carvalho Nacional, Carvalho Francês e Castanho, onde permanece durante os meses seguintes. O estágio mínimo é de 15 anos em cave, em madeira nova e em madeira usada.' },
    { uri: 'casal-garcia', images:['assets/imgs/casalgarcia.png','assets/imgs/alandra1.jpg','assets/imgs/alandra2.jpg'], name: 'Casal Garcia', title: 'Haja Alegria. Haja Casal Garcia!', description: 'Lançada em 1939, Casal Garcia é hoje uma marca icónica e uma das marcas com maior historial na Aveleda. Facilmente identificada pela sua garrafa de tom azulado e pelo seu rótulo único, Casal Garcia está presente em mais de 70 países e continua a ser um dos embaixadores dos vinhos Portugueses em todo o mundo.' }
  ];